### ISSUE TITLE
v3 error

### ISSUE THREAD

**Issue by mthenw** [mthenw/heroku-buildpack-vertx#1]
```
2015-04-02T11:49:05.098237+00:00 heroku[web.1]: Starting process with command `vertx run server.js`
2015-04-02T11:49:18.291386+00:00 app[web.1]: Failed in deploying verticle
2015-04-02T11:49:18.291410+00:00 app[web.1]:    at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:521)
2015-04-02T11:49:18.291404+00:00 app[web.1]: javax.script.ScriptException: Error: Cannot find module vertx in <eval> at line number 125 at column number 6
2015-04-02T11:49:18.291405+00:00 app[web.1]:    at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:586)
2015-04-02T11:49:18.291415+00:00 app[web.1]:    at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$154(DeploymentManager.java:424)
2015-04-02T11:49:18.291407+00:00 app[web.1]:    at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:570)
2015-04-02T11:49:18.291419+00:00 app[web.1]:    at io.vertx.core.impl.ContextImpl$$Lambda$6/2079278380.run(Unknown Source)
2015-04-02T11:49:18.291408+00:00 app[web.1]:    at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:525)
2015-04-02T11:49:18.291421+00:00 app[web.1]:    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
2015-04-02T11:49:18.291411+00:00 app[web.1]:    at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:192)
2015-04-02T11:49:18.291414+00:00 app[web.1]:    at io.vertx.lang.js.JSVerticleFactory$JSVerticle.start(JSVerticleFactory.java:96)
2015-04-02T11:49:18.291431+00:00 app[web.1]:    at jdk.nashorn.internal.objects.NativeError.constructor(NativeError.java:130)
2015-04-02T11:49:18.291412+00:00 app[web.1]:    at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
2015-04-02T11:49:18.291416+00:00 app[web.1]:    at io.vertx.core.impl.DeploymentManager$$Lambda$5/2771454.handle(Unknown Source)
2015-04-02T11:49:18.291424+00:00 app[web.1]:    at java.lang.Thread.run(Thread.java:745)
2015-04-02T11:49:18.291429+00:00 app[web.1]:    at jdk.nashorn.internal.objects.NativeError.<init>(NativeError.java:107)
2015-04-02T11:49:18.291428+00:00 app[web.1]:    at jdk.nashorn.internal.objects.NativeError.<init>(NativeError.java:103)
2015-04-02T11:49:18.291420+00:00 app[web.1]:    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
2015-04-02T11:49:18.291436+00:00 app[web.1]:    at jdk.nashorn.internal.scripts.Script$\^eval\_.L:21$Module$L:54(null:55)
2015-04-02T11:49:18.291437+00:00 app[web.1]:    at jdk.nashorn.internal.scripts.Script$\^eval\_#74\!17\^eval\_@0.L:1(server.js:1)
2015-04-02T11:49:18.291440+00:00 app[web.1]:    at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:378)
2015-04-02T11:49:18.291442+00:00 app[web.1]:    at jdk.nashorn.internal.scripts.Script$\^eval\_.L:21$_load(null:99)
2015-04-02T11:49:18.291417+00:00 app[web.1]:    at io.vertx.core.impl.ContextImpl.lambda$wrapTask$15(ContextImpl.java:260)
2015-04-02T11:49:18.291425+00:00 app[web.1]: Caused by: <eval>:125:6 Error: Cannot find module vertx
2015-04-02T11:49:18.291423+00:00 app[web.1]:    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
2015-04-02T11:49:18.291430+00:00 app[web.1]:    at jdk.nashorn.internal.objects.NativeError.<init>(NativeError.java:111)
2015-04-02T11:49:18.291433+00:00 app[web.1]:    at jdk.nashorn.internal.scripts.Script$\^eval\_.L:21$doRequire(null:125)
2015-04-02T11:49:18.291438+00:00 app[web.1]:    at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:545)
2015-04-02T11:49:18.291439+00:00 app[web.1]:    at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:209)
2015-04-02T11:49:18.291427+00:00 app[web.1]:    at jdk.nashorn.internal.objects.NativeError.initException(NativeError.java:138)
2015-04-02T11:49:18.291434+00:00 app[web.1]:    at jdk.nashorn.internal.scripts.Script$\^eval\_.L:21$Require(null:106)
2015-04-02T11:49:18.291435+00:00 app[web.1]:    at jdk.nashorn.internal.scripts.Script$\^eval\_.:scopeCall(null)
2015-04-02T11:49:18.291477+00:00 app[web.1]:    at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:378)
2015-04-02T11:49:18.291447+00:00 app[web.1]:    at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:535)
2015-04-02T11:49:18.291448+00:00 app[web.1]:    at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:209)
2015-04-02T11:49:18.291443+00:00 app[web.1]:    at jdk.nashorn.internal.scripts.Script$\^eval\_.L:21$doRequire(null:139)
2015-04-02T11:49:18.291445+00:00 app[web.1]:    at jdk.nashorn.internal.scripts.Script$\^eval\_.L:21$RequireNoCache(null:110)
2015-04-02T11:49:18.291446+00:00 app[web.1]:    at jdk.nashorn.internal.scripts.Script$\^eval\_.runScript(<eval>:1)
2015-04-02T11:49:18.291479+00:00 app[web.1]:    at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:568)
2015-04-02T11:49:18.291480+00:00 app[web.1]:    ... 13 more
2015-04-02T11:49:18.291481+00:00 app[web.1]:
```

**Comment by beders** [comment]
any solution to this yet?

**Comment by mthenw** [comment]
Nope, but I will be working on it tomorrow.

**Comment by mthenw** [comment]
I'm not planning to fix it, as I generally don't plan to maintain this repo any longer.
